namespace CXY.CJS.Application.Dtos
{
    public class ListLowerAgentOutputItem
    {
        public string WebSiteId { get; set; }
        public string Userid { get; set; }
        public string Username { get; set; }
        public string loginname { get; set; }
        public string Password { get; set; }
        public string PaymentPwd { get; set; }
        public string Safepassword { get; set; }
        public string Realname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Addtime { get; set; }
        public string Address { get; set; }
        public string Shortname { get; set; }
        public string Fullname { get; set; }
        public int Ispanuse { get; set; }
        public string Recommendusername { get; set; }
        public string Recommenduserid { get; set; }
        public string Cardno { get; set; }
        public int Isdelete { get; set; }
        public string Uptime { get; set; }
        public string UserRoleId { get; set; }
        public int UserProvince { get; set; }
        public int IsPaymentPwd { get; set; }
        public int Roleid { get; set; }
        public string Parentid { get; set; }
        public int Czfwsl { get; set; }
        public string Txzh { get; set; }
        public string Txkhx { get; set; }
        public string Txskr { get; set; }
        public string Txsj { get; set; }
        public int Isktskd { get; set; }
        public int Isktdd { get; set; }
        public string Userlayer { get; set; }
        public int Xjsl { get; set; }
        public string Dh { get; set; }
        public string Qq { get; set; }
        public string Scdlip { get; set; }
        public string Scdlsj { get; set; }
        public string Zcdlip { get; set; }
        public string Zcdlsj { get; set; }
        public int Isktpldr { get; set; }
        public int Viewdd { get; set; }
        public int Isktweixin { get; set; }
        public int Hirecar { get; set; }
        public int AlertWzxxlimit { get; set; }
        public int AlertWzxxKflimit { get; set; }
        public int AlertWzxxNewAdd { get; set; }
        public int CarCount { get; set; }
        public int UserMenuType { get; set; }
        public int IsBackQuery { get; set; }
        public int IsOffer { get; set; }
        public string ValidityDate { get; set; }
        public int BackQueryDay { get; set; }
        public string BackQueryBeginTime { get; set; }
        public int BackQueryFailAgainNumber { get; set; }
        public int BackQueryFailAgainInterval { get; set; }
        public bool BackQueryFailAgainMorning { get; set; }
        public string Swfzr { get; set; }
        public string DdCalculationType { get; set; }
        public string NDdCalculationType { get; set; }
        public int PriceFirst { get; set; }
        public int AutoBillShield { get; set; }
        public int IsSendSms { get; set; }
        public string Provinceid { get; set; }
        public float WapDifferenceThreshold { get; set; }
        public float WapDifferenceAbsolute { get; set; }
        public int WapDifferencePercentage { get; set; }
        public int IsOpenUsPrice { get; set; }
        public int UsPriceFareFirst { get; set; }
        public int UsPriceFareSecond { get; set; }
        public int IsGetOrder { get; set; }
        public int IsOpenExaminedPrice { get; set; }
        public int OnlineExaminedPrice { get; set; }
        public int UnOnlineExaminedPrice { get; set; }
        public int IsReceiveOrderSms { get; set; }
        public int IsReceiveCapitalSms { get; set; }
        public int IsReceiveAssetsSms { get; set; }
        public int IsReceivePowerSMS { get; set; }
        public int IsReceiveMakeSms { get; set; }
        public int PointsBillShield { get; set; }
        public int AnnualExpireReminder { get; set; }
        public int CompulsorExpireReminder { get; set; }
        public int CommercialExpireReminder { get; set; }
        public int IsRevice { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public bool H5AutoRecharge { get; set; }
        public string WeChatSubscription { get; set; }
        public bool WeiXinPayH5 { get; set; }
        public string Operator { get; set; }
        public string CxySellerAppUserId { get; set; }
        public int IsOpenKfOffer { get; set; }
        public int IsShenZhou { get; set; }
        public int IsOpenBkfOffer { get; set; }
        public int WarnYe { get; set; }
        public int WarnJf { get; set; }
        public int WarnDx { get; set; }
        public int BatchAskPriceMenu { get; set; }
        public int IsInvoice { get; set; }
        public int RateType { get; set; }
        public float Rate { get; set; }
        public int Drzsjf { get; set; }
        public string Drzsrq { get; set; }
        public int Drzssyjf { get; set; }
        public int Wdjf { get; set; }
        public int Rzsjf { get; set; }
        public float JfPrice { get; set; }
        public float NotePrice { get; set; }
        public int NoteNumber { get; set; }
        public int GivePointsPerMonth { get; set; }
        public int GivePointsSameMonth { get; set; }
        public int GivePointsSurplusSameMonth { get; set; }

        public float Wdye { get; set; }
        public float Overdrftamount { get; set; }
        public string ProfitJson { get; set; }
        public float Gdlr { get; set; }
        public int PriceFirstType { get; set; }
        public string Txyh { get; set; }
        public object UserCity { get; set; }
    }
}