using System;
using System.Collections.Generic;

namespace CXY.CJS.Model
{
    public  class Orders
    {
        public string WebSiteId { get; set; }
        public string Orderid { get; set; }
        public string Hpjc { get; set; }
        public string Hphm { get; set; }
        public string Hpzl { get; set; }
        public string Hpzlmc { get; set; }
        public string Cjh { get; set; }
        public string Fdjh { get; set; }
        public string Wfsj { get; set; }
        public string Wfcs { get; set; }
        public string Wsbh { get; set; }
        public string Wfdd { get; set; }
        public string Wflb { get; set; }
        public string Wzdm { get; set; }
        public int? Kf { get; set; }
        public decimal? Fkje { get; set; }
        public decimal? Znj { get; set; }
        public int? Kscl { get; set; }
        public decimal? Ksclf { get; set; }
        public decimal? Fwf { get; set; }
        public decimal? Fwf1 { get; set; }
        public decimal? Fwf2 { get; set; }
        public decimal? Hjfy { get; set; }
        public DateTime? Created { get; set; }
        public string Memo { get; set; }
        public string Proxy { get; set; }
        public string Proxyname { get; set; }
        public decimal? Proxyfwf { get; set; }
        public string Handle { get; set; }
        public string Batchid { get; set; }
        public int? Batchwzs { get; set; }
        public decimal? Ddzk { get; set; }
        public decimal? Sj { get; set; }
        public decimal? Wzlr { get; set; }
        public string Wflx { get; set; }
        public string Uniquecode { get; set; }
        public string Zfh { get; set; }
        public string Paytype { get; set; }
        public int? Issure { get; set; }
        public string Sure { get; set; }
        public string Surename { get; set; }
        public string Suretime { get; set; }
        public int? Fsbl { get; set; }
        public decimal? Fsblje { get; set; }
        public int? Isfirst { get; set; }
        public string Locationid { get; set; }
        public string ReMark { get; set; }
        public bool? PrivateFlag { get; set; }
        public string ReviseId { get; set; }
        public int? PriceFirst { get; set; }
        public string PriceSource { get; set; }
        public string Wfnr { get; set; }
        public string Ddbjid { get; set; }
        public string ExcelBatchId { get; set; }
        public string ExcelFrom { get; set; }
        public string ExcelFrombatch { get; set; }
        public string ExcelFromPrice { get; set; }
        public string ExcelFromMemo { get; set; }
        public string FwfBasis { get; set; }
        public DateTime? Proxytime { get; set; }
        public decimal? Difference { get; set; }
        public decimal? CostPrice { get; set; }
        public decimal? TotalFare { get; set; }
        public int? OrderSource { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public string DriverNo { get; set; }
        public int NeedMakeUpPrice { get; set; }
        public int NeedMakeUpData { get; set; }
        public decimal NeedMakeUpProxyFare { get; set; }
        public string NeedMakeUpSurePeople { get; set; }
        public int NeedMakeUpSureState { get; set; }
        public decimal NeedMakeUpFactPay { get; set; }
        public string NeedMakeDataEnum { get; set; }
        public decimal? TotalDifference { get; set; }
        public string NeedMakeUpFirstMemo { get; set; }
        public string NeedMakeUpSecondMemo { get; set; }
        public string Phone { get; set; }
        public decimal? Proxyfkje { get; set; }
        public string UserMemo { get; set; }
        public string AlreadyMakeDataEnum { get; set; }
        public DateTime? MakeUpPriceTime { get; set; }
        public DateTime? MakeUpDataTime { get; set; }
        public int? IsOutViolation { get; set; }
        public int? MakeUpTimes { get; set; }
        public string OldBatchid { get; set; }
        public decimal? InPoundage { get; set; }
        public int? IsFavorablePrice { get; set; }
        public string FavorablePriceInfo { get; set; }
        public decimal? LastTimePoundage { get; set; }
        public decimal? Vat { get; set; }
        public decimal? TaxRate { get; set; }
        public int? IsInvoice { get; set; }
        public int IsShenzhou { get; set; }
        public int? PriceFrom { get; set; }
        public int? OrderByNo { get; set; }
        public string TailUserId { get; set; }
        public string TailUserName { get; set; }
        public string ViolationId { get; set; }
        public int? OrderFrom { get; set; }
    }
}
